import { useState, useRef, useMemo } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import { useToast } from '../components/ui/Toast'
import { useConfirm } from '../components/ui/ConfirmDialog'
import {
  Plus, Pencil, Trash2, X, Upload, Download, Search,
  Users, AlertTriangle, FileText,
} from 'lucide-react'

// ── constants ─────────────────────────────────────────────────────────────────
const CURRENT_YEAR = new Date().getFullYear().toString()
const inputCls = `w-full border border-gray-300 rounded-lg px-3 py-2 text-sm
  focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent transition bg-white`

// Registration number is auto-generated by the database trigger

// ── data fetchers ─────────────────────────────────────────────────────────────
const fetchStudents = async () => {
  const { data, error } = await supabase
    .from('students')
    .select('*, classes(id,name,level), combinations(id,code,full_name)')
    .order('full_name')
  if (error) throw error
  return data
}
const fetchClasses = async () => {
  const { data, error } = await supabase.from('classes').select('*').order('level').order('name')
  if (error) throw error
  return data
}
const fetchCombinations = async () => {
  const { data, error } = await supabase.from('combinations').select('*').order('code')
  if (error) throw error
  return data
}

// ── CSV helpers ───────────────────────────────────────────────────────────────
const CSV_HEADERS = ['full_name','gender','date_of_birth','class_name','combination_code','enrollment_year']

function downloadTemplate() {
  const rows = [
    CSV_HEADERS.join(','),
    `John Doe,M,2008-01-15,Form 1,,${CURRENT_YEAR}`,
    `Jane Smith,F,2008-03-22,Form 2,,${CURRENT_YEAR}`,
    `Alice Mbeki,F,2006-07-10,Form 5,PCB,${CURRENT_YEAR}`,
  ]
  const blob = new Blob([rows.join('\n')], { type: 'text/csv' })
  const a = Object.assign(document.createElement('a'), {
    href: URL.createObjectURL(blob),
    download: 'mufumbu_students_template.csv',
  })
  a.click()
  URL.revokeObjectURL(a.href)
}

function parseCSV(text) {
  const lines = text.trim().split(/\r?\n/)
  if (lines.length < 2) return { headers: [], rows: [] }
  const headers = lines[0].split(',').map(h => h.trim().toLowerCase().replace(/\s+/g,'_'))
  const rows = lines.slice(1).filter(l => l.trim()).map((line, i) => {
    // handle quoted fields with commas
    const values = []
    let cur = '', inQ = false
    for (const ch of line) {
      if (ch === '"') { inQ = !inQ }
      else if (ch === ',' && !inQ) { values.push(cur.trim()); cur = '' }
      else cur += ch
    }
    values.push(cur.trim())
    return { _row: i + 2, ...Object.fromEntries(headers.map((h, j) => [h, values[j] ?? ''])) }
  })
  return { headers, rows }
}

// ── shared primitives ─────────────────────────────────────────────────────────
function Modal({ title, onClose, wide, children }) {
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center p-4 bg-black/40 overflow-y-auto">
      <div className={`bg-white rounded-2xl shadow-xl w-full my-4 ${wide ? 'max-w-2xl' : 'max-w-md'}`}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 sticky top-0 bg-white rounded-t-2xl">
          <h3 className="font-semibold text-gray-900">{title}</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition"><X size={18} /></button>
        </div>
        <div className="px-6 py-5">{children}</div>
      </div>
    </div>
  )
}

function Field({ label, required, hint, children }) {
  return (
    <div className="space-y-1.5">
      <label className="block text-sm font-medium text-gray-700">
        {label}{required && <span className="text-red-500 ml-0.5">*</span>}
        {hint && <span className="ml-2 text-xs text-gray-400 font-normal">{hint}</span>}
      </label>
      {children}
    </div>
  )
}

// ── StudentForm (add / edit) ──────────────────────────────────────────────────
function StudentForm({ initial, classes, combinations, onClose }) {
  const qc    = useQueryClient()
  const toast = useToast()

  const [form, setForm] = useState({
    full_name:       initial?.full_name      ?? '',
    gender:          initial?.gender          ?? '',
    date_of_birth:   initial?.date_of_birth  ?? '',
    class_id:        initial?.class_id        ?? '',
    combination_id:  initial?.combination_id  ?? '',
    enrollment_year: initial?.enrollment_year ?? CURRENT_YEAR,
  })
  const [err, setErr] = useState('')
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  const selectedClass = classes.find(c => c.id === parseInt(form.class_id))
  const isALevel = selectedClass?.level === 'a_level'

  const save = useMutation({
    mutationFn: async () => {
      setErr('')
      if (!form.full_name.trim()) throw new Error('Full name is required.')
      if (!form.class_id)         throw new Error('Class is required.')

      const payload = {
        full_name:       form.full_name.trim(),
        gender:          form.gender || null,
        date_of_birth:   form.date_of_birth || null,
        class_id:        parseInt(form.class_id),
        combination_id:  isALevel && form.combination_id ? parseInt(form.combination_id) : null,
        enrollment_year: form.enrollment_year || CURRENT_YEAR,
      }

      if (initial) {
        const { error } = await supabase.from('students').update(payload).eq('id', initial.id)
        if (error) throw error
      } else {
        const { error } = await supabase.from('students').insert(payload)
        if (error) throw error
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['students'] })
      toast.success(initial ? `${form.full_name} updated successfully.` : `${form.full_name} registered successfully.`)
      onClose()
    },
    onError: e => { setErr(e.message); toast.error(e.message) },
  })

  return (
    <>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {err && (
          <div className="sm:col-span-2 flex items-start gap-2 bg-red-50 border border-red-200 text-red-700 rounded-lg px-3 py-2 text-sm">
            <AlertTriangle size={15} className="shrink-0 mt-0.5" />{err}
          </div>
        )}

        {initial?.registration_number && (
          <div className="sm:col-span-2 flex items-center gap-2 bg-gray-50 border border-gray-200 rounded-lg px-3 py-2 text-sm">
            <span className="text-gray-500 text-xs font-medium">Reg. No:</span>
            <span className="font-mono font-semibold text-gray-800">{initial.registration_number}</span>
            <span className="ml-auto text-xs text-gray-400">Auto-generated</span>
          </div>
        )}

        <Field label="Full name" required>
          <input className={inputCls} value={form.full_name}
            onChange={e => set('full_name', e.target.value)} placeholder="John Doe" />
        </Field>

        <Field label="Gender">
          <select className={inputCls} value={form.gender} onChange={e => set('gender', e.target.value)}>
            <option value="">— Select —</option>
            <option value="M">Male</option>
            <option value="F">Female</option>
          </select>
        </Field>

        <Field label="Date of birth" hint="YYYY-MM-DD">
          <input type="date" className={inputCls} value={form.date_of_birth}
            onChange={e => set('date_of_birth', e.target.value)} />
        </Field>

        <Field label="Class" required>
          <select className={inputCls} value={form.class_id}
            onChange={e => { set('class_id', e.target.value); set('combination_id', '') }}>
            <option value="">— Select class —</option>
            {['o_level','a_level'].map(lvl => (
              <optgroup key={lvl} label={lvl === 'o_level' ? 'O-Level (Form 1–4)' : 'A-Level (Form 5–6)'}>
                {classes.filter(c => c.level === lvl).map(c => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </optgroup>
            ))}
          </select>
        </Field>

        <Field label="Enrollment year">
          <input className={inputCls} value={form.enrollment_year}
            onChange={e => set('enrollment_year', e.target.value)} placeholder={CURRENT_YEAR} maxLength={4} />
        </Field>

        {isALevel && (
          <Field label="Combination" hint="A-Level only" className="sm:col-span-2">
            <select className={inputCls} value={form.combination_id} onChange={e => set('combination_id', e.target.value)}>
              <option value="">— Select combination —</option>
              {combinations.map(c => (
                <option key={c.id} value={c.id}>{c.code} — {c.full_name}</option>
              ))}
            </select>
          </Field>
        )}
      </div>

      <div className="flex gap-3 mt-6">
        <button onClick={onClose} className="flex-1 border border-gray-300 text-gray-700 rounded-xl py-2.5 text-sm font-medium hover:bg-gray-50 transition">Cancel</button>
        <button onClick={() => save.mutate()} disabled={save.isPending}
          className="flex-1 bg-green-700 hover:bg-green-600 text-white rounded-xl py-2.5 text-sm font-semibold transition disabled:opacity-60">
          {save.isPending ? 'Saving…' : initial ? 'Save changes' : 'Register student'}
        </button>
      </div>
    </>
  )
}

// ── CSV Import Modal ──────────────────────────────────────────────────────────
function CSVImportModal({ classes, combinations, onClose }) {
  const qc      = useQueryClient()
  const toast   = useToast()
  const fileRef = useRef()

  const [rows, setRows]       = useState([])   // parsed rows
  const [errors, setErrors]   = useState([])   // per-row validation errors
  const [step, setStep]       = useState('upload') // 'upload' | 'preview'
  const [importing, setImporting] = useState(false)
  const [result, setResult]   = useState(null)  // { imported, failed }

  const classMap = useMemo(() =>
    Object.fromEntries(classes.map(c => [c.name.toLowerCase(), c])), [classes])
  const comboMap = useMemo(() =>
    Object.fromEntries(combinations.map(c => [c.code.toLowerCase(), c])), [combinations])

  const handleFile = e => {
    const file = e.target.files[0]
    if (!file) return
    if (!file.name.endsWith('.csv')) { toast.error('Please upload a .csv file.'); return }

    const reader = new FileReader()
    reader.onload = ev => {
      const { rows: parsed } = parseCSV(ev.target.result)
      const validated = parsed.map(r => {
        const errs = []
        if (!r.full_name)  errs.push('Full name required')
        if (!r.class_name) errs.push('Class name required')
        if (r.gender && !['m','f'].includes(r.gender.toLowerCase())) errs.push('Gender must be M or F')

        const cls = classMap[r.class_name?.toLowerCase()]
        if (r.class_name && !cls) errs.push(`Class "${r.class_name}" not found`)

        const combo = r.combination_code ? comboMap[r.combination_code?.toLowerCase()] : null
        if (r.combination_code && !combo) errs.push(`Combination "${r.combination_code}" not found`)

        return { ...r, _class: cls, _combo: combo, _errors: errs }
      })

      const allErrors = validated.filter(r => r._errors.length > 0)
      setRows(validated)
      setErrors(allErrors)
      setStep('preview')
    }
    reader.readAsText(file)
  }

  const handleImport = async () => {
    const valid = rows.filter(r => r._errors.length === 0)
    if (valid.length === 0) { toast.error('No valid rows to import.'); return }

    setImporting(true)
    let imported = 0, failed = 0

    for (const r of valid) {
      try {
        const payload = {
          full_name:       r.full_name.trim(),
          gender:          r.gender ? r.gender.toUpperCase() : null,
          date_of_birth:   r.date_of_birth || null,
          class_id:        r._class.id,
          combination_id:  r._combo?.id ?? null,
          enrollment_year: r.enrollment_year || CURRENT_YEAR,
        }
        const { error } = await supabase.from('students').insert(payload)
        if (error) throw error
        imported++
      } catch {
        failed++
      }
    }

    qc.invalidateQueries({ queryKey: ['students'] })
    setResult({ imported, failed, total: valid.length })
    setImporting(false)

    if (failed === 0) toast.success(`Import complete: ${imported} student(s) registered.`)
    else toast.warning(`Import done with issues: ${imported} registered, ${failed} failed.`)
  }

  if (result) {
    return (
      <>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Registered', value: result.imported, color: 'bg-green-50 border-green-200 text-green-700' },
              { label: 'Failed',     value: result.failed,   color: 'bg-red-50 border-red-200 text-red-700' },
            ].map(s => (
              <div key={s.label} className={`border rounded-xl p-4 text-center ${s.color}`}>
                <p className="text-2xl font-bold">{s.value}</p>
                <p className="text-xs font-medium mt-0.5">{s.label}</p>
              </div>
            ))}
          </div>
          {result.failed > 0 && (
            <p className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
              {result.failed} row(s) failed. Check for duplicate registration numbers or missing data.
            </p>
          )}
        </div>
        <button onClick={onClose} className="w-full mt-6 bg-green-700 hover:bg-green-600 text-white rounded-xl py-2.5 text-sm font-semibold transition">
          Done
        </button>
      </>
    )
  }

  return (
    <>
      {step === 'upload' && (
        <div className="space-y-5">
          {/* Instructions */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 space-y-2">
            <p className="text-sm font-semibold text-blue-800 flex items-center gap-2">
              <FileText size={15} /> CSV Format Instructions
            </p>
            <ul className="text-xs text-blue-700 space-y-1 list-disc list-inside">
              <li>First row must be the header row (column names)</li>
              <li><strong>full_name</strong> — student's full name (required)</li>
              <li><strong>gender</strong> — M or F</li>
              <li><strong>date_of_birth</strong> — format: YYYY-MM-DD</li>
              <li><strong>class_name</strong> — must match exactly: Form 1, Form 2, … Form 6 (required)</li>
              <li><strong>combination_code</strong> — A-Level only: PCB, HEG, etc. (leave blank for O-Level)</li>
              <li><strong>enrollment_year</strong> — 4-digit year, e.g. {CURRENT_YEAR}</li>
              <li>Registration numbers are <strong>auto-generated</strong> by the system</li>
            </ul>
          </div>

          {/* Download template */}
          <button onClick={downloadTemplate}
            className="w-full flex items-center justify-center gap-2 border-2 border-dashed border-green-300
                       hover:border-green-500 text-green-700 hover:bg-green-50 rounded-xl py-3 text-sm font-semibold transition">
            <Download size={16} /> Download CSV Template
          </button>

          {/* File upload */}
          <div>
            <p className="text-sm font-medium text-gray-700 mb-2">Upload your completed CSV</p>
            <label className="flex flex-col items-center justify-center gap-2 border-2 border-dashed
                             border-gray-300 hover:border-green-400 rounded-xl py-8 cursor-pointer
                             hover:bg-gray-50 transition">
              <Upload size={24} className="text-gray-400" />
              <span className="text-sm text-gray-500">Click to select a .csv file</span>
              <input ref={fileRef} type="file" accept=".csv" className="sr-only" onChange={handleFile} />
            </label>
          </div>
        </div>
      )}

      {step === 'preview' && (
        <div className="space-y-4">
          {/* Summary */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Total rows',   value: rows.length,                          color: 'bg-gray-50 border-gray-200 text-gray-700' },
              { label: 'Valid',        value: rows.filter(r => !r._errors.length).length, color: 'bg-green-50 border-green-200 text-green-700' },
              { label: 'With errors',  value: errors.length,                        color: errors.length ? 'bg-red-50 border-red-200 text-red-700' : 'bg-gray-50 border-gray-200 text-gray-400' },
            ].map(s => (
              <div key={s.label} className={`border rounded-xl p-3 text-center ${s.color}`}>
                <p className="text-xl font-bold">{s.value}</p>
                <p className="text-xs font-medium mt-0.5">{s.label}</p>
              </div>
            ))}
          </div>

          {/* Errors */}
          {errors.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-3 max-h-36 overflow-y-auto space-y-1">
              <p className="text-xs font-semibold text-red-700 mb-2">Rows with errors (will be skipped):</p>
              {errors.map(r => (
                <div key={r._row} className="text-xs text-red-600">
                  <strong>Row {r._row}:</strong> {r._errors.join('; ')}
                </div>
              ))}
            </div>
          )}

          {/* Preview table */}
          <div>
            <p className="text-xs font-semibold text-gray-500 mb-2">Preview (first 5 valid rows)</p>
            <div className="overflow-x-auto border border-gray-200 rounded-xl">
              <table className="w-full text-xs">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    {['Name', 'Gender', 'Class', 'Combination', 'Year'].map(h => (
                      <th key={h} className="text-left px-3 py-2 font-semibold text-gray-600">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {rows.filter(r => !r._errors.length).slice(0,5).map((r, i) => (
                    <tr key={i} className="hover:bg-gray-50">
                      <td className="px-3 py-2 text-gray-800">{r.full_name}</td>
                      <td className="px-3 py-2 text-gray-600">{r.gender || '—'}</td>
                      <td className="px-3 py-2 text-gray-600">{r.class_name}</td>
                      <td className="px-3 py-2 text-gray-600">{r.combination_code || '—'}</td>
                      <td className="px-3 py-2 text-gray-600">{r.enrollment_year || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="flex gap-3">
            <button onClick={() => { setStep('upload'); setRows([]); setErrors([]); if(fileRef.current) fileRef.current.value='' }}
              className="flex-1 border border-gray-300 text-gray-700 rounded-xl py-2.5 text-sm font-medium hover:bg-gray-50 transition">
              ← Back
            </button>
            <button onClick={handleImport} disabled={importing || rows.filter(r=>!r._errors.length).length === 0}
              className="flex-1 bg-green-700 hover:bg-green-600 text-white rounded-xl py-2.5 text-sm font-semibold transition disabled:opacity-60 flex items-center justify-center gap-2">
              {importing ? (
                <><svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                </svg> Importing…</>
              ) : `Import ${rows.filter(r=>!r._errors.length).length} student(s)`}
            </button>
          </div>
        </div>
      )}
    </>
  )
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function DashboardStudents() {
  const qc      = useQueryClient()
  const toast   = useToast()
  const confirm = useConfirm()

  const [search, setSearch]     = useState('')
  const [levelFilter, setLevel] = useState('all')
  const [classFilter, setClass] = useState('all')
  const [addOpen, setAddOpen]   = useState(false)
  const [editStudent, setEdit]  = useState(null)
  const [csvOpen, setCsvOpen]   = useState(false)

  const { data: students = [],    isLoading: loadingS } = useQuery({ queryKey: ['students'],    queryFn: fetchStudents })
  const { data: classes = [],     isLoading: loadingC } = useQuery({ queryKey: ['classes'],     queryFn: fetchClasses })
  const { data: combinations = [] }                     = useQuery({ queryKey: ['combinations'], queryFn: fetchCombinations })

  const delStudent = useMutation({
    mutationFn: id => supabase.from('students').delete().eq('id', id),
    onSuccess: (_, id) => {
      const name = students.find(s => s.id === id)?.full_name ?? 'Student'
      qc.invalidateQueries({ queryKey: ['students'] })
      toast.success(`"${name}" removed successfully.`)
    },
    onError: e => toast.error(`Failed to delete: ${e.message}`),
  })

  // filtered list
  const filtered = useMemo(() => students.filter(s => {
    const q = search.toLowerCase()
    const matchSearch = !q || s.full_name.toLowerCase().includes(q) || s.registration_number.toLowerCase().includes(q)
    const matchLevel  = levelFilter === 'all' || s.classes?.level === levelFilter
    const matchClass  = classFilter === 'all' || String(s.class_id) === classFilter
    return matchSearch && matchLevel && matchClass
  }), [students, search, levelFilter, classFilter])

  const oCount = students.filter(s => s.classes?.level === 'o_level').length
  const aCount = students.filter(s => s.classes?.level === 'a_level').length

  return (
    <div className="space-y-5">
      {/* Modals */}
      {addOpen && (
        <Modal title="Register student" wide onClose={() => setAddOpen(false)}>
          <StudentForm classes={classes} combinations={combinations} onClose={() => setAddOpen(false)} />
        </Modal>
      )}
      {editStudent && (
        <Modal title="Edit student" wide onClose={() => setEdit(null)}>
          <StudentForm initial={editStudent} classes={classes} combinations={combinations} onClose={() => setEdit(null)} />
        </Modal>
      )}
      {csvOpen && (
        <Modal title="Import students from CSV" wide onClose={() => setCsvOpen(false)}>
          <CSVImportModal classes={classes} combinations={combinations} onClose={() => setCsvOpen(false)} />
        </Modal>
      )}

      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Students</h2>
          <p className="text-sm text-gray-500 mt-0.5">Register and manage enrolled students</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={() => setCsvOpen(true)}
            className="flex items-center gap-2 border border-gray-300 bg-white hover:bg-gray-50 text-gray-700
                       text-sm font-medium px-4 py-2 rounded-lg transition">
            <Upload size={15} /> Import CSV
          </button>
          <button onClick={() => setAddOpen(true)}
            className="flex items-center gap-2 bg-green-700 hover:bg-green-600 text-white
                       text-sm font-semibold px-4 py-2 rounded-lg transition">
            <Plus size={16} /> Add student
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Total students', value: students.length, color: 'text-gray-800' },
          { label: 'O-Level',        value: oCount,          color: 'text-blue-700' },
          { label: 'A-Level',        value: aCount,          color: 'text-purple-700' },
        ].map(s => (
          <div key={s.label} className="bg-white border border-gray-200 rounded-xl px-4 py-4">
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="text-xs text-gray-500 mt-0.5">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-48">
          <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input className="w-full pl-9 pr-4 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-green-500 bg-white"
            placeholder="Search by name or reg. number…"
            value={search} onChange={e => setSearch(e.target.value)} />
        </div>
        <select className="border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-green-500"
          value={levelFilter} onChange={e => { setLevel(e.target.value); setClass('all') }}>
          <option value="all">All levels</option>
          <option value="o_level">O-Level</option>
          <option value="a_level">A-Level</option>
        </select>
        <select className="border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-green-500"
          value={classFilter} onChange={e => setClass(e.target.value)}>
          <option value="all">All classes</option>
          {classes.filter(c => levelFilter === 'all' || c.level === levelFilter).map(c => (
            <option key={c.id} value={String(c.id)}>{c.name}</option>
          ))}
        </select>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        {loadingS || loadingC ? (
          <div className="py-20 text-center text-gray-400 text-sm">Loading students…</div>
        ) : filtered.length === 0 ? (
          <div className="py-20 text-center space-y-3">
            <Users size={36} className="mx-auto text-gray-300" />
            <p className="text-gray-400 text-sm">
              {students.length === 0 ? 'No students registered yet.' : 'No students match your filters.'}
            </p>
            {students.length === 0 && (
              <div className="flex justify-center gap-3">
                <button onClick={() => setAddOpen(true)} className="text-sm text-green-700 underline">Add manually</button>
                <span className="text-gray-300">|</span>
                <button onClick={() => setCsvOpen(true)} className="text-sm text-green-700 underline">Import CSV</button>
              </div>
            )}
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50">
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Reg. Number</th>
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Full Name</th>
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Gender</th>
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Class</th>
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Combination</th>
                  <th className="text-left font-semibold text-gray-600 px-4 py-3">Year</th>
                  <th className="px-4 py-3 w-20" />
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filtered.map(s => (
                  <tr key={s.id} className="hover:bg-gray-50 transition">
                    <td className="px-4 py-3 font-mono text-xs text-gray-600">{s.registration_number}</td>
                    <td className="px-4 py-3 font-medium text-gray-900">{s.full_name}</td>
                    <td className="px-4 py-3">
                      {s.gender
                        ? <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${s.gender === 'M' ? 'bg-blue-100 text-blue-700' : 'bg-pink-100 text-pink-700'}`}>{s.gender === 'M' ? 'Male' : 'Female'}</span>
                        : <span className="text-gray-400 text-xs">—</span>}
                    </td>
                    <td className="px-4 py-3">
                      {s.classes && (
                        <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${s.classes.level === 'o_level' ? 'bg-blue-100 text-blue-700' : 'bg-purple-100 text-purple-700'}`}>
                          {s.classes.name}
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-gray-600 text-xs">
                      {s.combinations ? `${s.combinations.code}` : <span className="text-gray-300">—</span>}
                    </td>
                    <td className="px-4 py-3 text-gray-500 text-xs">{s.enrollment_year ?? '—'}</td>
                    <td className="px-4 py-3">
                      <div className="flex items-center justify-end gap-0.5">
                        <button onClick={() => setEdit(s)} className="p-1.5 text-gray-400 hover:text-blue-600 transition rounded"><Pencil size={15} /></button>
                        <button onClick={async () => {
                          const ok = await confirm({
                            title: `Delete ${s.full_name}?`,
                            message: `This will permanently remove "${s.full_name}" (${s.registration_number}) and all their results. This cannot be undone.`,
                            confirmLabel: 'Delete',
                          })
                          if (ok) delStudent.mutate(s.id)
                        }} className="p-1.5 text-gray-400 hover:text-red-600 transition rounded">
                          <Trash2 size={15} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="px-4 py-3 border-t border-gray-100 text-xs text-gray-400">
              Showing {filtered.length} of {students.length} students
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
